FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY ReviewProducer/pom.xml .
COPY ReviewProducer/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/ReviewProducer-1.0-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]