FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY ReviewConsumer/pom.xml .
COPY ReviewConsumer/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/ReviewConsumer-1.0-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]