{
 "title": "Sentiment Trends",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "product",
    "label": "Product",
    "query": "GTA_6,FC_26,CALL_OF_DUTY,FORZA_HORIZON_6"
   }
  ]
 },
 "panels": [
  {
   "title": "Raw Sentiment Scores",
   "type": "timeseries",
   "description": "Every review Sentiment Score plotted over time of $product.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  sentiment_score AS \"Sentiment Score\",\n  product\nFROM\n  review_analysis\nWHERE\n  product IN ($product)\nORDER BY\n  id;"
    }
   ]
  },
  {
   "title": "Smart Weighted Score",
   "type": "timeseries",
   "description": "How  Smart Weighted Score evolves over time of $product.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  product,\n  smart_weighted_score AS \"Smart Weighted Score\"\nFROM\n  product_ranking\nWHERE\n  product IN ($product)\nORDER BY\n  timestamp;"
    }
   ]
  },
  {
   "title": "Rolling Average (15 Reviews)",
   "type": "timeseries",
   "description": "Smoothed sentiment using a 15 review sliding window of $product. Each point is the average of 15 reviews.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  product,\n  AVG(sentiment_score) OVER (\n    PARTITION BY product\n    ORDER BY\n      timestamp ROWS BETWEEN 14 PRECEDING\n      AND CURRENT ROW\n  ) AS \"Rolling Avg\"\nFROM\n  review_analysis\nWHERE\n  product IN ($product)\nORDER BY\n  timestamp;"
    }
   ]
  },
  {
   "title": "Unweighted vs Weighted Average Sentiment Score",
   "type": "barchart",
   "description": "Compares unweighted average vs weighted average of $product.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  product AS \"Product\",\n  ROUND(AVG(sentiment_score) :: numeric, 1) AS \"Unweighted\",\n  ROUND(\n    (SUM(sentiment_score * weight) / SUM(weight)) :: numeric,\n    1\n  ) AS \"Weighted\"\nFROM\n  review_analysis\nWHERE\n  product IN ($product)\nGROUP BY\n  product\nORDER BY\n  product;"
    }
   ]
  }
 ]
}